[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "cdis"
version = "1.0.0"
requires-python = ">=3.10"


[dependency-groups]
dev = ["pytest>8", "coverage", "tox", "ruff"]


[pytest]
testpaths="tests"
